version: "3"

services:
  app:
    image: rl_demos:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
#    working_dir: /rl_demos/demos
    command:
      - /bin/sh
      - -c
      - |
        pwd 
        ls 
        python rl_demo.py --gym_env BipedalWalker-v3 --demo_type continuous