lr: 2.54e-4
num_envs: 80
num_steps: 128 # how much data to collect in a rollout. each policy rollout is num_envs*num_steps = 4*128=512
batch_size: 512 # num_envs * num_steps = 4*128=512
total_timesteps: 250000

gae: True
gamma: 0.99
gae_lambda: 0.95

num_mini_batch: 4
minibatch_size: 128 # batch_size // num_mini_batch
update_epochs: 4

clip_coef: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5

logging: False
gym_id: Acrobot-v1
resume: False
target_kl: None
